### PR TITLE
Report code coverage to coveralls

### PR DESCRIPTION
**Pull request by kadel**
quick fix for Coveralls problem 
#287

### CODE REVIEW

**Comment by sebgoa** [comment]
LGTM

**Comment by kadel** [comment]
lets wait untill travis job finishes.

I only tested this on my fork.

**Comment by kadel** [comment]
Wheeee, it works ;-)

Only down side is that number it reports is  coverage of lines from files that have tests.
So packages without any tests are not included in this.

**Comment by kadel** [comment]
This was quickest solution that I could think of. 
It would be great to get something little bit cleaner.

**Pull request merged**
