### PR TITLE
Switch from godep to glide

### LINKED ISSUE #314: Replace godep with glide
We had a lot of issues with `godep` it is time to switch to `glide`.
If we use `glide` we can get rid of ugly [godep-restore.sh](https://github.com/kubernetes-incubator/kompose/blob/master/script/godep-restore.sh)

### PR DESCRIPTION
**Pull request by kadel**
fixed #314

I tried to use Glide instead of Godep, setting up was surprisingly easy.
With only one catch: You need to run `glide update` with `--strip-vendor` otherwise glide keeps vendor directories inside kompose vendor dir (`/vendor/.../vendor/...`) In some project this can be useful, but kompose can't be build whit this.
Overall I really like glide.

**But** (there is always but :sunglasses: )
It looks like glide is not striping unused code from vendored dependencies , like godep does.
with glide vendor is **277M** :-(
with godep it was **52M**

https://github.com/sgotti/glide-vc might help with that. (haven't tried yet)
Or we can remove vendor from git as @ngtuna suggested [here](https://github.com/kubernetes-incubator/kompose/pull/297#issuecomment-263586556). But I expressed my view there. I think it is better to keep vendor in project repo.

### CODE REVIEW

**Comment by surajssd** [comment]
I am +1 on keeping `vendor` dir as it is and not removing it from kompose.

**Comment by ngtuna** [comment]
So with this PR should we delete the PR #297 ?

**Comment by kadel** [comment]
So there is a reason why glide doesn't strip dependencies. 
It explained here http://engineeredweb.com/blog/2016/go-why-not-strip-unused-pkgs/
But I don't know if that is valid point or not.

**Comment by kadel** [comment]
updated this PR with glide-vc cleanup.
vendor is now 32M

**Comment by kadel** [comment]
I will add some docs to this PR explaining how to add and update dependencies

**Comment by ericchiang** [comment]
you'll probably want to squash those commits, or git will still track the removed objects.

**Comment by kadel** [comment]
@ericchiang yes that is the plan, I will definitely squash this before merge.

@ngtuna I'll add short docs and probably scripts that will wrap glide and glide-vc. Than I'll ping you for another review. :wink:

**Comment by kadel** [comment]
I've added docs and scripts that validate if vendor is clean.

It is ready for another review.
ping @ngtuna

**Comment by sebgoa** [comment]
@technosophos could you advise us with this ?

**Comment by technosophos** [comment]
/cc @mattfarina (who volunteered to look at this on SIG-Apps).

This looks good to me. If you're checking in vendor, then glide-vc is a great way to manage that. And everything else looks great.

**Comment by surajssd** [comment]
@technosophos so can we go ahead with merging this?

**Comment by technosophos** [comment]
I have no reason to object to merging this, though I'm not a core maintainer on this project.

**Comment by ngtuna** [comment]
@surajssd I think we can let it passed now. @kadel can you merge?

**Comment by cdrage** [comment]
@ngtuna He's away until after the new year, so you'll have to merge or we could wait until he's back :)

**Comment by surajssd** [comment]
@technosophos @ngtuna @cdrage thank you merging this in.

**Comment by ngtuna** [comment]
oh I see. So could you also take a look into #317 @surajssd @cdrage ?

**Pull request merged**
