### PR TITLE
remove duplicate import with different name

### PR DESCRIPTION
**Pull request by surajssd**
`k8s.io/kubernetes/pkg/api` is imported directly and once with the alias import name `kapi` so remove the original import and keep the aliased with `kapi` one and also replace the code bits which call it with `api` name.

### CODE REVIEW

**Comment by cdrage** [comment]
LGTM.

**Comment by surajssd** [comment]
@cdrage you will have to approve it to merge it!

**Comment by cdrage** [comment]
@surajssd Got to wait for one more approval.

@surajnarwade @kadel @containscafeine @rtnpro ?

**Comment by surajssd** [comment]
@cdrage thanks :+1:

**Comment by cdrage** [comment]
@surajssd Try to wait until 2 people approve it :+1: before any merges :)

**Comment by surajssd** [comment]
@cdrage sure ! I thought this is smaller one, with mainly name changes so merged it!

**Pull request merged**
