### PR TITLE
kompose up/down create and delete pvc

### LINKED ISSUE #218: PVCs are not created when calling `kompose up`

### PR DESCRIPTION
**Pull request by surajssd**
pvc will be parsed when passing objects via kube client to create various objects. Also while deleting pvc will be deleted.

Fixes #218

### CODE REVIEW

**Comment by dustymabe** [comment]
was trying to test this for openshift but seems like this change is only for kube - should we update both at the same time?

**Comment by dustymabe** [comment]
also managed to get this error - but not sure where it came from: 

```
[dustymabe@media examples (dusty-mlbparks)]$ ../kompose up
We are going to create Kubernetes deployments and services for your Dockerized application. 
If you need different kind of resources, use the 'kompose convert' and 'kubectl create -f' commands instead. 

INFO[0000] Successfully created service: redis          
INFO[0000] Successfully created service: web            
INFO[0000] Successfully created deployment: redis       
INFO[0000] Successfully created deployment: web         

Your application has been deployed to Kubernetes. You can run 'kubectl get deployment,svc,pods' for details.
[dustymabe@media examples (dusty-mlbparks)]$ ../kompose down 
INFO[0000] Successfully deleted service: redis          
INFO[0003] Successfully deleted deployment: redis       
FATA[0003] Error while deleting application: no reaper has been implemented for { PersistentVolumeClaim}
```

**Comment by surajssd** [comment]
@dustymabe sorry for not labeling it, so creating a PVC was easy thing to do, but looking at how can I delete it, it's not straightforward like other objects, so stuck on it right now, so mostly following code from `kubectl`

**Comment by surajssd** [comment]
So I need some review here with respect to how `Undeploy` is implemented, I feel even for undeploy we should get converted objects iterate on those and then type switch on it and delete objects, cleanly. The problem here is that with komposeObject there is no way to identify how many PVCs were created? And since the names of PVC follow index starting from 0. There is no easy way to understand their names. So I propose here to change current implementation to implementation similar to `Deploy` its just that instead of create we call delete.

**Comment by dustymabe** [comment]
hey suraj - this is working for openshift now :) - one thing though. should we modify the following line to include `pvc`  for both kube and openshift? 

```
Your application has been deployed to OpenShift. You can run 'oc get dc,svc,is' for details.
```

**Comment by surajssd** [comment]
@dustymabe sure done for k8s as well! That's nice catch!

Never mind https://github.com/kubernetes-incubator/kompose/pull/220#issuecomment-255124733 check latest changes!

**Comment by dustymabe** [comment]
> Never mind #220 (comment) check latest changes!

so you figured out how to go about doing the undeploy?

**Comment by surajssd** [comment]
@dustymabe yes with @kadel 's help got some pointers earlier today from old code that once @ngtuna did here https://github.com/kubernetes-incubator/kompose/blob/e08ab06f2c1dacf2bae477bb5faace2feb387c90/pkg/transformer/kubernetes/kubernetes.go#L298

**Comment by dustymabe** [comment]
up/down seems to be working for me now. I'm good with this - just need a maintainer to review.

**Comment by dustymabe** [comment]
ping @ngtuna @janetkuo @kadel

**Comment by ngtuna** [comment]
Code LGTM. Haven't tested yet but @dustymabe did it.

**Comment by surajssd** [comment]
@kadel done! https://github.com/kubernetes-incubator/kompose/pull/220/files#diff-08d4e6a1922a157aca193e75416bbb9cR48

Also merging :) Thanks @dustymabe @kadel and @ngtuna for reviewing!

**Pull request merged**
