### PR TITLE
add missing 'io.kompose.service' label to Route and Ingress

### LINKED ISSUE #510: kompose down is not deleting ingress and route

### PR DESCRIPTION
**Pull request by kadel**
This was caussing 'kompose down' not to delete Route and Ingress

fixes #510

### CODE REVIEW

**Comment by procrypt** [comment]
@kadel I tried this out but seems it doesn't delete the route in OpenShift :(

**Comment by kadel** [comment]
really? 
I just tried that again, and it is working for me.

**Comment by surajnarwade** [comment]
@kadel , @procrypt I tried this and it works for me :)
@procrypt , I think you created route manually.

**Comment by kadel** [comment]
ping @cdrage @procrypt @surajssd

**Comment by procrypt** [comment]
Ah this works for me now, tested again, @kadel LGTM.

**Comment by cdrage** [comment]
LGTM :+1:

**Pull request merged**
