### PR TITLE
Add bash auto completion support

### PR DESCRIPTION
**Pull request by cdrage**
Adds auto completion support that's generated via:
```
$ kompose complete
```

This file is added to /etc/bash_completion.d/kompose.sh

### CODE REVIEW

**Comment by cdrage** [comment]
Closes https://github.com/kubernetes-incubator/kompose/issues/37

**Comment by cdrage** [comment]
@ngtuna It should. Doesn't look like you're running as sudo / have user permission to /etc/bash_completion.d/

**Comment by ngtuna** [comment]
Ah see it now... It doesn't work on Mac. Could we add this support to darwin ?

**Comment by surajssd** [comment]
works on fedora for me :+1:

**Comment by kadel** [comment]
Can we do it like `kubectl` or `oc`? Print to stdout instead to file? (https://kubernetes.io/docs/user-guide/kubectl/kubectl_completion/) or at least have option for it.

Second thing is that I don't think that it is no nice write to `/etc` by default without any warning.

**Comment by kadel** [comment]
And one more. Some people are using ZSH (like me for example :wink: )

**Comment by cdrage** [comment]
@kadel Alright :) I'll do these three things:

1. Output to stdout
2. Add the ZSH option (btw @kadel zsh > bash. #zshmasterrace)
3. Add support for Darwin

**Comment by cdrage** [comment]
@ngtuna @kadel 

Ready for another review!

It now:

1. Outputs to stdout :+1: 
2. Added bash support :+1: 
3. For the users who use a laptop with a magical touchbar that removes the ESC key, you can simple source it with `source <(kompose completion bash)`. :+1:

**Comment by cdrage** [comment]
@kadel 

Tests should be all green now (validate error with some unreachable code). 

I've also updated the README with the appropriate instructions on how to use this!

Merge when you're ready :+1:

**Comment by kadel** [comment]
LGTM @ngtuna can you confirm?

**Comment by ngtuna** [comment]
Yes. Confirmed

**Pull request merged**
