### PR TITLE
Move docker-compose.yml test file to tests

### PR DESCRIPTION
**Pull request by cdrage**
Moves a file that was incorrectly being used from examples to
script/test/fixtures.

### CODE REVIEW

**Comment by cdrage** [comment]
Unblocks #528

**Comment by kadel** [comment]
it might be better to move ` script/test/docker-compose.yml` to its own directory in `fixtures` so its inline with other tests

**Comment by cdrage** [comment]
@kadel Done! Moved it to `redis-example`.

**Comment by cdrage** [comment]
There, tests should pass now!

**Comment by cdrage** [comment]
Woo :+1:

**Pull request merged**
