### PR TITLE
Add ARM to make cross.

### PR DESCRIPTION
**Pull request by cdrage**
This adds a linux/arm build to Makefile which will be included in the
release.sh script.

### CODE REVIEW

**Comment by cdrage** [comment]
ping @surajnarwade and @kadel 

Would need a quick review of this before I release 0.5.0 today :)

**Comment by surajnarwade** [comment]
#541

**Comment by cdrage** [comment]
Hey @surajnarwade and @kadel 

I'm going to go ahead and merge this in so I can do the 0.5.0 release today!

**Comment by surajnarwade** [comment]
LGTM :)

**Pull request merged**
