### PR TITLE
godeps: remove quotes from one entry

### PR DESCRIPTION
**Pull request by dustymabe**

### CODE REVIEW

**Comment by sebgoa** [comment]
@kadel @ngtuna can we edit godeps.json manually ?

**Comment by kadel** [comment]
@surajssd you shouldn't edit it manually, i don't have idea how that happend :-(

But this will be also solved by https://github.com/kubernetes-incubator/kompose/pull/297

**Comment by ngtuna** [comment]
@sebgoa yes we can but it doesn't recommend.

**Comment by dustymabe** [comment]
ok feel free to close when this is resolved by the other issue/PR then

**Comment by surajssd** [comment]
@dustymabe thanks, this is resolved in other PR!

**Pull request closed without merging**
