### PR TITLE
support parse key-only environment variable

### LINKED ISSUE #303: kompose 0.1.2 fails to parse key-only variables in environment section, does work with lists but generates invalid k8s resources
`kompose version 0.1.2 (92ea047)`

I was exciting to try out kompose to help my colleague migrate to k8s, but I could not find any of our dock-compose files that kompose could parse. They all reported errors for the 'environment' section, such as:

```
ERRO[0000] Could not parse config for project project : yaml: line 88: could not find expected ':'
```
or
```
FATA[0000] Failed to load compose file: Service 'mysql' configuration key 'environment' contains an invalid type, it should be an array or object
Service 'phpmyadmin' configuration key 'environment' contains an invalid type, it should be an array or object
Unsupported config option for phpmyadmin service: 'PMA_HOST'
```

It looks like the kompose parser doesn't support the full docker-compose spec for environment variables. If you want to pass your build environment value into the same-named environment variable in your container, you just need to name the variable in the environment section of the docker-compose file, e.g.

```
    environment:
      MYSQL_HOST
      MYSQL_DATABASE
      MYSQL_USER
      MYSQL_PASSWORD
```

This is documented in the docker-compose spec page for environment variables here:

https://docs.docker.com/compose/compose-file/#/environment
**"Environment variables with only a key are resolved to their values on the machine Compose is running on, which can be helpful for secret or host-specific values."**

I was able to work around this for the kompose parser by adding colons to each item, but I think that might break docker-compose as all the variables will get blank/empty values.
```
    environment:
      MYSQL_HOST:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
```

Converting the environment section to a sequence also helped kompose parse it, though again not sure if docker-compose will support this form?
```
    environment:
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
```

But even with both those work-arounds kompose generated only name fields for kubernetes, with no value, which isn't going to work when sent to a cluster. 

```
                "env": [
                  {
                    "name": "MYSQL_DATABASE"
                  },
                  {
                    "name": "MYSQL_USER"
                  },
                  {
                    "name": "MYSQL_PASSWORD"
                  },
                  {
                    "name": "MYSQL_ROOT_PASSWORD"
                  }
                ],
```

I think kompose should generate value properties with the actual value of the environment variables (from the kompose environment).

When we manually convert docker-compose file some of those environment fields become Secret or ConfigMap entries, but probably injecting the value is best default behavior for kompose is order to allow `kompose up` to work?

### PR DESCRIPTION
**Pull request by ngtuna**
fix #303

### CODE REVIEW

**Comment by kadel** [comment]
:+1: 
But can you please also add unit test for this?

**Comment by sebgoa** [comment]
yeah, let's blocked everything until we get in the habit of making sure we have unit tests...

**Comment by ngtuna** [comment]
ok so @kadel I added the unit test. Please take a look.

**Comment by ngtuna** [comment]
Tks @cdrage Rebased!

**Comment by cdrage** [comment]
LGTM :+1:

**Comment by ngtuna** [comment]
@cdrage please approve again then I can merge it.

**Comment by cdrage** [comment]
@ngtuna I can approve, but since I still don't have access to @kubernetes-incubator it wont appear as :+1: / green.

**Comment by ngtuna** [comment]
@cdrage I see :-(

**Comment by surajssd** [comment]
Also three more conditions that are not tested: 


```bash
env: "foo:bar=foobar"     name: "foo" val: "bar=foobar"
env: "foo=foo:bar"        name: "foo" val: "foo:bar"

env: "foo:"               name: "foo" val: ""
```

**Comment by ngtuna** [comment]
@surajssd Added and rebased. Please take a look.

**Pull request merged**
