### PR TITLE
Added default input file as docker-compose.yml

### PR DESCRIPTION
**Pull request by surajssd**
There was missing default docker-compose.yml so added it.

Fixes https://github.com/kubernetes-incubator/kompose/issues/369

### CODE REVIEW

**Comment by surajssd** [comment]
@rtnpro @procrypt is there a better way to do it? Because @procrypt is also working on https://github.com/kubernetes-incubator/kompose/pull/368 so want it to be easy in both places.

**Comment by rtnpro** [comment]
@surajssd this looks good to me :+1:

**Comment by cdrage** [comment]
LGTM :+1:

**Comment by kadel** [comment]
In the way how  #366  is right now implemented, change in this PR will break #366

**Comment by kadel** [comment]
In the way how  #368  is right now implemented, change in this PR will break #368

**Comment by surajssd** [comment]
@kadel @rtnpro closing this one since https://github.com/kubernetes-incubator/kompose/pull/368 solves it.

**Pull request closed without merging**
