### PR TITLE
Update vendoring for libcompose and others

### PR DESCRIPTION
**Pull request by cdrage**
This updates the vendoring for libcompose because of the result of
https://github.com/docker/libcompose/pull/457 and
https://github.com/docker/libcompose/pull/450 being merged upstream.

### CODE REVIEW

**Comment by cdrage** [comment]
ping @surajnarwade

**Comment by cdrage** [comment]
Restarting build since Travis messed up (Fedora git servers were down, so it was unable to pull the submodule)

**Comment by kadel** [comment]
with https://github.com/docker/libcompose/pull/450 merged  we will  have to update how we handle build context. Our implementation is based on wrong implementation in libcompose :-) Fixing it in libcompose broke our code :-(

**Comment by kadel** [comment]
this vendor update should be probably handled by  https://github.com/kubernetes-incubator/kompose/pull/454/ with all proper fixes

**Comment by cdrage** [comment]
@kadel Yeah, just realized after lunch that this won't do. Closing for now and doing it via #454

**Pull request closed without merging**
