### PR TITLE
Added flag definitions for kompose #37

### PR DESCRIPTION
**Pull request by cab105**

### CODE REVIEW

**Comment by ngtuna** [comment]
@cab105 I'm gonna refuse this PR because you was doing it in the keynote.

**Comment by cab105** [comment]
At least I'm doing something productive while paying attention.

**Comment by ngtuna** [comment]
So tell me what Kelsey was talking at his keynote section? :trollface:

**Comment by cab105** [comment]
What is kubeadm for 100 @ngtuna?

**Comment by ngtuna** [comment]
Tested. LGTM

**Pull request merged**
