### PR TITLE
Update openshift, openshift k8s deps in Godeps and vendors.

### PR DESCRIPTION
**Pull request by rtnpro**
Steps followed to update Godeps:

``` bash
cd $GOPATH/src/github.com/openshift/origin; git checkout v1.4.0-rc1; ./hack/godep-restore.sh
cd $GOPATH/src/github.com/docker/docker; git checkout 601004e1a714d77d3a43e957b8ae8adbc867b280 # from existing Godeps.json
cd $GOPATH/src/github.com/docker/engine-api; git checkout 1d247454d4307fb1ddf10d09fd2996394b085904 # from Godeps.json
cd $GOPATH/src/github.com/kubernetes-incubator/kompose
# To avoid errors during saving dependencies
rm -rf Godeps
godep save ./... 
```

### CODE REVIEW

**Comment by containscafeine** [comment]
@rtnpro, running `script/godep-restore.sh` fails with this -

```bash
<snip>
Starting to download all godeps. This takes a while
# cd /home/concaf/rtn_pr_godep/src/google.golang.org/cloud; git checkout eb47ba841d53d93506cfbfbc03927daf9cc48f88
godep: error restoring dep (google.golang.org/cloud/compute/metadata): chdir /home/concaf/rtn_pr_godep/src/google.golang.org/cloud: no such file or directory
# cd /home/concaf/rtn_pr_godep/src/google.golang.org/cloud; git checkout eb47ba841d53d93506cfbfbc03927daf9cc48f88
godep: error restoring dep (google.golang.org/cloud/internal): chdir /home/concaf/rtn_pr_godep/src/google.golang.org/cloud: no such file or directory
godep: Error restoring some deps. Aborting check.
```

**Comment by surajssd** [comment]
@containscafeine this was in a clean GOPATH ?

**Comment by containscafeine** [comment]
@surajssd Yessir!

**Comment by sebgoa** [comment]
@kadel should have a look at this. I believe there is an issue with our dependencies, we seem to be pulling way more than we need.

**Comment by kadel** [comment]
I got same error as @containscafeine.

**Comment by kadel** [comment]
I'm fairly confused about this. If i do `godep restore` again after i get that error, everything works fine

**Comment by rtnpro** [comment]
@kadel @surajssd I found a related issue with godeps here: https://github.com/tools/godep/issues/186

It seems like ``godep`` complains if it's not able to download or find the package. However, on the second run, it works. I am not sure how to work around this issue.

**Comment by surajssd** [comment]
@rtnpro this worked for me on a clean GOPATH.

**Comment by kadel** [comment]
@rtnpro @containscafeine @surajssd 
can you please check https://github.com/kadel/kompose/tree/update-godeps-openshift-k8s?
It is modified godep-restore.sh (more in comments) and it should fix this.

Right now I don't see any other way how to fix this :-(

Will do more testing tomorrow.

**Comment by surajssd** [comment]
@kadel did try your script and it worked without problems.

```bash
[vagrant@fedora ~]$ ll
total 12
drwxrwxr-x. 2 vagrant vagrant 4096 Nov 24 06:12 Downloads
drwxrwxr-x. 5 vagrant vagrant 4096 Nov 24 12:40 go
-rwxrwxr-x. 1 vagrant vagrant 3152 Nov 24 06:31 installer_go.sh
[vagrant@fedora ~]$ rm -rf $GOPATH/src

[vagrant@fedora ~]$ mkdir -p $GOPATH/src/github.com/kubernetes-incubator
[vagrant@fedora ~]$ cd $GOPATH/src/github.com/kubernetes-incubator

[vagrant@fedora kubernetes-incubator]$ git clone https://github.com/kadel/kompose
Cloning into 'kompose'...
remote: Counting objects: 8992, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 8992 (delta 0), reused 0 (delta 0), pack-reused 8986
Receiving objects: 100% (8992/8992), 7.67 MiB | 1.75 MiB/s, done.
Resolving deltas: 100% (3954/3954), done.
Checking connectivity... done.


[vagrant@fedora kubernetes-incubator]$ cd kompose/
✔ ~/go/src/github.com/kubernetes-incubator/kompose [master|✔]
18:11 $ git checkout update-godeps-openshift-k8s 
Branch update-godeps-openshift-k8s set up to track remote branch update-godeps-openshift-k8s from origin.
Switched to a new branch 'update-godeps-openshift-k8s'

✔ ~/go/src/github.com/kubernetes-incubator/kompose [update-godeps-openshift-k8s|✔] 
18:12 $ ./script/godep-restore.sh 
Preloading some dependencies
remote: Counting objects: 6704, done.
remote: Total 6704 (delta 3386), reused 3386 (delta 3386), pack-reused 3318
Receiving objects: 100% (6704/6704), 3.36 MiB | 1.40 MiB/s, done.
Resolving deltas: 100% (5103/5103), completed with 1444 local objects.
From https://github.com/openshift/kubernetes
 * [new branch]      master     -> github.com/openshift-remote/master
 * [new branch]      openshift-1.3 -> github.com/openshift-remote/openshift-1.3
 * [new branch]      openshift-1.4 -> github.com/openshift-remote/openshift-1.4
 * [new branch]      rebase-20160831 -> github.com/openshift-remote/rebase-20160831
 * [new branch]      release-1.0 -> github.com/openshift-remote/release-1.0
 * [new branch]      release-1.1 -> github.com/openshift-remote/release-1.1
 * [new branch]      release-1.2 -> github.com/openshift-remote/release-1.2
 * [new branch]      release-1.2-stable-20160309 -> github.com/openshift-remote/release-1.2-stable-20160309
 * [new branch]      release-1.2-stable-20160312 -> github.com/openshift-remote/release-1.2-stable-20160312
 * [new branch]      release-1.2-stable-20160316 -> github.com/openshift-remote/release-1.2-stable-20160316
 * [new branch]      stable     -> github.com/openshift-remote/stable
 * [new branch]      stable-20160127 -> github.com/openshift-remote/stable-20160127
 * [new branch]      stable-20160211 -> github.com/openshift-remote/stable-20160211
 * [new branch]      stable-20160309 -> github.com/openshift-remote/stable-20160309
 * [new branch]      stable-20160411 -> github.com/openshift-remote/stable-20160411
 * [new branch]      stable-20160510 -> github.com/openshift-remote/stable-20160510
 * [new branch]      stable-20160615 -> github.com/openshift-remote/stable-20160615
 * [new branch]      stable-20160624 -> github.com/openshift-remote/stable-20160624
 * [new branch]      stable-20160804 -> github.com/openshift-remote/stable-20160804
 * [new branch]      stable-20160831 -> github.com/openshift-remote/stable-20160831
 * [new branch]      stable-9da202e -> github.com/openshift-remote/stable-9da202e
 * [new tag]         v1.1.0-origin -> v1.1.0-origin
 * [new tag]         v1.2.0-origin -> v1.2.0-origin
remote: Counting objects: 3, done.
remote: Total 3 (delta 2), reused 2 (delta 2), pack-reused 1
Unpacking objects: 100% (3/3), done.
From https://github.com/openshift/glog
 * [new branch]      master     -> github.com/openshift-remote/master
 * [new branch]      stable     -> github.com/openshift-remote/stable
Note: checking out 'eb47ba8'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at eb47ba8... metadata: use ctxhttp to support cancelation in Go 1.4
Starting to download all godeps. This takes a while
Download finished into /home/vagrant/go

✔ ~/go/src/github.com/kubernetes-incubator/kompose [update-godeps-openshift-k8s|✔] 
18:27 $ 
```

**Comment by kadel** [comment]
I've added my changes to godep-restore.sh to this PR

**Comment by kadel** [comment]
Can we get more reviews on this?
This is quite big.

fixes #297 


As soon as we fix current state with `godeps` we can start working on switching to `glide` ( #314)

cc: @rtnpro @surajssd @ngtuna @janetkuo

**Comment by ngtuna** [comment]
Hi @kadel I have another approach for this. Let's not try to fix the current Godeps, just remove vendor and Godeps folders and start building glide. We should list out here dependencies and theirs version that Kompose relies on and then build glide.yaml file. Focusing on main packages, others we could use latest version. So here we have:

- libcompose v0.3.0-68-gfbdac0a (could be upgraded to v0.3.0)
- kubernetes/openshift 1.3 (probably we should upgrade to 1.4)
- spf13/cobra master

Once having the fixed dependencies, we will test the current codebase and make changes if it's needed.

**Comment by kadel** [comment]
Problem is that it is broken now, and until we make glide work, we can't do restore and work with dependencies.

 I think that we should fix this first. Especially when we already have fix.

Than we can work on making it work with glide.

**Comment by rtnpro** [comment]
So, let's merge it :)

**Comment by ngtuna** [comment]
Okay. So I just tested this PR in a separate folder and it worked. Didn't look into files.

```
Tunas-MacBook-Pro:kompose tuna$ git branch
  master
* rtnpro-update-godeps-openshift-k8s
Tunas-MacBook-Pro:kompose tuna$ go build -o kompose main.go 

Tunas-MacBook-Pro:kompose tuna$ pwd
/tmp/gocode/kompose/src/github.com/kubernetes-incubator/kompose

Tunas-MacBook-Pro:kompose tuna$ script/godep-restore.sh 
Preloading some dependencies
remote: Counting objects: 6704, done.
remote: Total 6704 (delta 3383), reused 3383 (delta 3383), pack-reused 3321
Receiving objects: 100% (6704/6704), 3.39 MiB | 963.00 KiB/s, done.
Resolving deltas: 100% (5102/5102), completed with 1443 local objects.
From https://github.com/openshift/kubernetes
 * [new branch]      master        -> github.com/openshift-remote/master
 * [new branch]      openshift-1.3 -> github.com/openshift-remote/openshift-1.3
 * [new branch]      openshift-1.4 -> github.com/openshift-remote/openshift-1.4
 * [new branch]      rebase-20160831 -> github.com/openshift-remote/rebase-20160831
 * [new branch]      release-1.0   -> github.com/openshift-remote/release-1.0
 * [new branch]      release-1.1   -> github.com/openshift-remote/release-1.1
 * [new branch]      release-1.2   -> github.com/openshift-remote/release-1.2
 * [new branch]      release-1.2-stable-20160309 -> github.com/openshift-remote/release-1.2-stable-20160309
 * [new branch]      release-1.2-stable-20160312 -> github.com/openshift-remote/release-1.2-stable-20160312
 * [new branch]      release-1.2-stable-20160316 -> github.com/openshift-remote/release-1.2-stable-20160316
 * [new branch]      stable        -> github.com/openshift-remote/stable
 * [new branch]      stable-20160127 -> github.com/openshift-remote/stable-20160127
 * [new branch]      stable-20160211 -> github.com/openshift-remote/stable-20160211
 * [new branch]      stable-20160309 -> github.com/openshift-remote/stable-20160309
 * [new branch]      stable-20160411 -> github.com/openshift-remote/stable-20160411
 * [new branch]      stable-20160510 -> github.com/openshift-remote/stable-20160510
 * [new branch]      stable-20160615 -> github.com/openshift-remote/stable-20160615
 * [new branch]      stable-20160624 -> github.com/openshift-remote/stable-20160624
 * [new branch]      stable-20160804 -> github.com/openshift-remote/stable-20160804
 * [new branch]      stable-20160831 -> github.com/openshift-remote/stable-20160831
 * [new branch]      stable-9da202e -> github.com/openshift-remote/stable-9da202e
 * [new tag]         v1.1.0-origin -> v1.1.0-origin
 * [new tag]         v1.2.0-origin -> v1.2.0-origin
remote: Counting objects: 3, done.
remote: Total 3 (delta 2), reused 2 (delta 2), pack-reused 1
Unpacking objects: 100% (3/3), done.
From https://github.com/openshift/glog
 * [new branch]      master     -> github.com/openshift-remote/master
 * [new branch]      stable     -> github.com/openshift-remote/stable
Note: checking out 'eb47ba8'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at eb47ba8... metadata: use ctxhttp to support cancelation in Go 1.4
Starting to download all godeps. This takes a while
Download finished into /tmp/gocode/kompose
```

**Comment by sebgoa** [comment]
Before we merge this, can we have a discussion on whether we really need all these dependencies. I have not spend much time with Godeps...but it looks like the project is getting bigger and bigger with dependencies going down the rabbit hole...

Like do we really need all of openshift and all of Kubernetes (plus a ton of other things) to compile ?

**Comment by ngtuna** [comment]
@sebgoa that's also what I wanted to mention on above suggestion. Like what I did with Glide, I listed out mandatory packages relating directly to our code and build Glide file from the scratch. The pain of dependency problem is that these packages will require other packages. But that's fine. Maintaining only packages relating directly to kompose code would be a good approach. And we should not upload vendor folder, let's users install deps on their own machine.

**Comment by kadel** [comment]
> And we should not upload vendor folder, let's users install deps on their own machine.

Please don't do that.

We should upload vendor folder, it is intended to be included in project repo.
If you don't include vendor in your project git repository, it is easy to break build.
If someone deletes library that you depend on you can still build your project because that code is in your vendor dir.

**Comment by kadel** [comment]
> Like do we really need all of openshift and all of Kubernetes (plus a ton of other things) to compile ?

Kompose just imports bunch of pkgs  from:
 - k8s.io/kubernetes
 - gitub.com/openshif/origin
 - github.com/docker/libcompose

Problem is that those brings their dependencies, dependencies of those dependencies ...  it gets complicated especially with OpenShift and Kubernetes in one project.

List of actual dependencies is generated by godep.
I wouldn't be surprised if there is a lot of dependencies that are not required, but godeps includes them for some reason. Glide might be better in this.  But right now, this is what we get with godep.

I will try to do this again to verify that i get same result as rtnpro got.

**Comment by kadel** [comment]
I found out that there are really packages in `vendor` and in `Godeps.json` that are not used.
I did fresh `godep-restore.sh` and `godep save ./...` and not this PR removes more lines that  adds ;-)

**Comment by kadel** [comment]
@sebgoa  I did fresh `godep-restore.sh` and `godep save ./...` and I got less dependencies than @rtnpro  got.
I don't understand how it is possible :confused: but somehow it is, and everything seems to be working.

Now this PR removes more lines that it adds.

**Comment by ngtuna** [comment]
> We should upload vendor folder, it is intended to be included in project repo.
If you don't include vendor in your project git repository, it is easy to break build.

Yeah that's also correct. We could probably make travis pulling deps on every build but yes it will slow down the build process.

**Comment by surajssd** [comment]
I think this is not required any more. @rtnpro closing it.

**Pull request closed without merging**
