### PR TITLE
Add io.kompose.service label to every object & use reaper to delete BuildConfig

### LINKED ISSUE #382: kompose down with openshift doesn't delete  BuildConfig
I tried running `kompose down` with the buildconfig example here: https://github.com/kubernetes-incubator/kompose/tree/master/examples/buildconfig

It doesn't delete the buildconfig. 

```bash
$ kompose --provider=openshift -f docker-compose.yml down
WARN[0000] [foo] Service cannot be created because of missing port. 
INFO[0000] Buildconfig using https://github.com/skippbox/kompose2.git::master as source. 
INFO[0001] Successfully deleted DeploymentConfig: foo   
INFO[0001] Successfully deleted ImageStream: foo
```
```bash
$ oc get bc
NAME      TYPE      FROM         LATEST
foo       Docker    Git@master   1
```

### PR DESCRIPTION
**Pull request by kadel**
- Add  `io.kompose.service` label to BuildConfig, DaemonSet, ReplicationController and Pod.
 - Use reaper to delete BuildConfig (deletes also pods used for build)

Now every object created by Kompose should have this label.
Only some of the objects had this label before. This fixes #382

### CODE REVIEW

**Comment by kadel** [comment]
@surajssd `template.ObjectMeta.Labels = transformer.ConfigLabels(name)`  sets labels only for `PodTemplate` in controller object, but on for object itself.


But I will update this PR so labels are set in one place in this function and not for every object separately as its now.

**Comment by surajssd** [comment]
@kadel oh yes, thanks for clarifying that one.

**Comment by kadel** [comment]
ping @cdrage @surajssd @procrypt @containscafeine

**Comment by cdrage** [comment]
I don't see anything wrong with the code, testing it, it works as intended!

LGTM!

**Pull request merged**
