### PR TITLE
index.md: made LoadBalancer Ingress a valid IPv4

### PR DESCRIPTION
**Pull request by ceocoder**

### CODE REVIEW

**Comment by ceocoder** [comment]
I signed it!

**Comment by cdrage** [comment]
@ceocoder thanks man, good find!

**Comment by ceocoder** [comment]
@cdrage np, years of watching Hollywood movies and saying "Wait! that is not a real IP!" made it easy.  Like this one,

hackers

**Comment by cdrage** [comment]
meirl

**Pull request merged**
