### PR TITLE
Changing printf verb in compose_test.go

### LINKED ISSUE #654: make test is failing
When I run make test I'm getting this error
```bash
$ make test
go get github.com/mattn/goveralls
go get github.com/modocache/gover
go get github.com/Masterminds/glide
go get github.com/sgotti/glide-vc
go get github.com/golang/lint/golint
./script/check-vendor.sh
Checking for nested vendor dirs
OK
Checking if vendor was cleaned using glide-vc.
OK
./script/check-gofmt.sh
gofmt OK
go vet ./pkg/... ./cmd/... .
pkg/loader/compose/compose_test.go:67: arg expected for printf verb %s of wrong type: github.com/kubernetes-incubator/kompose/pkg/kobject.Ports
exit status 1
Makefile:75: recipe for target 'vet' failed
make: *** [vet] Error 1
```

### PR DESCRIPTION
**Pull request by procrypt**
Fixes #654 
cc: @surajssd @cdrage @kadel @surajnarwade

### CODE REVIEW

**Comment by surajnarwade** [comment]
LGTM

**Comment by cdrage** [comment]
LGTM

**Comment by procrypt** [comment]
Hey @cdrage can we merge it since it's blocker to #640

**Comment by cdrage** [comment]
@procrypt I just tested this locally and it doesn't fix `vet`..

**Comment by cdrage** [comment]
Well, I mean, it solves the first one! Merging.

**Comment by procrypt** [comment]
@cdrage Thanks :)

**Pull request merged**
