### PR TITLE
Remove version column from conversion document

### PR DESCRIPTION
**Pull request by cdrage**
Removes the version column in order to expand the width of the
conversion document as well as indicate that the table expands on ALL
versions (1,2,3)

### CODE REVIEW

**Comment by surajnarwade** [comment]
after expanding, it looks good now

**Comment by surajssd** [comment]
Table looks like this right now!
screenshot from 2017-05-29 15-18-45

**Comment by cdrage** [comment]
@surajssd Ah shoot. I'll fix it.

**Comment by cdrage** [comment]
@surajssd @surajnarwade Fixed. I've also added spacing for those reading directly from a non-formatted markdown file.

Feel free to check it out now.

**Comment by cdrage** [comment]
https://github.com/cdrage/kompose/blob/update-table/docs/conversion.md

**Comment by surajssd** [comment]
cool this LGTM!

**Pull request merged**
