### PR TITLE
Update imports to reflect move to kubernetes-incubator

### PR DESCRIPTION
**Pull request by kadel**

### CODE REVIEW

**Comment by surajssd** [comment]
LGTM! Press that magic green button!

**Comment by dustymabe** [comment]
one sec:
```
$ grep -R skippbox | head -n 3
script/.validate:       VALIDATE_REPO='https://github.com/skippbox/kompose.git'
script/.build:BUILD_FLAGS=(-tags experimental -ldflags="-w -X github.com/skippbox/kompose/version.GITCOMMIT=${GITCOMMIT}")
Godeps/Godeps.json:     "ImportPath": "github.com/skippbox/kompose",
```

**Comment by kadel** [comment]
@dustymabe Good catch. I just check *.go files.

**Comment by kadel** [comment]
I've updated original commit to include files that I've missed.
I've also added new commit updating links in docs and readme.

**Comment by dustymabe** [comment]
LGTM

**Comment by sebgoa** [comment]
+1 LGTM

let's merge it , I am testing the build right now, so we can fix quickly if there are remaining issues.

**Comment by sebgoa** [comment]
@kadel your write privileges should have transferred....you should try to merge it so we can test that as well ...

**Comment by sebgoa** [comment]
merging for tomas, because he is not in front of his computer and we need a working build after the move.

**Pull request merged**
