### PR TITLE
Adds Kompose.io website

### PR DESCRIPTION
**Pull request by cdrage**
This commit adds the kompose.io website including introduction and setup
instructions.

### CODE REVIEW

**Comment by cdrage** [comment]
Some notes:

- This is pushed to the gh-pages branch (for GitHub pages)
- I have parked the domain kompose.io
- This will add a website for Kompose with a basic introduction and setup page.
- In the future, blog post(s) can be added, more information pushed. As of right now, it's a quick "30-second" spiel to get the person's attention.
- This is not meant to replace any documentation on here and is meant as an alternative landing page for Kompose. In the future, syncing the `/docs` directory to the site would be the most ideal
- If you want to test it out, simply run `jekyll serve .`

Here's an included preview of what it looks like:
image

**Comment by cdrage** [comment]
ping @kubernetes-incubator/maintainers-kompose

**Comment by ngtuna** [comment]
It looks great. Thanks @cdrage . I did test it on my machine. But I think we should display another better example: guestbook or voting app ?

**Comment by cdrage** [comment]
@ngtuna I feel as though an example like that is too overly-complex to be on a simple introduction page. Having a quick "understand in 30 seconds" page is the best answer.

Once I add new pages, I believe we should have a more elaborate example such as the voting app or guestbook application.

**Comment by sebgoa** [comment]
I agree with tuna there should be a better 30 seconds example. Something that does not ask people to download a random image from a guy called "tuna" :)

**Comment by cdrage** [comment]
@sebgoa @ngtuna 

Added the Guestbook example! Feel free to have a look :) Once this is merged I can modify this repo to have the kompose.io domain point here.

**Comment by kadel** [comment]
It looks like step 2.1 is not correctly formatted. 

screenshot from 2017-01-19 16-14-27

**Comment by cdrage** [comment]
@kadel You're right xD http://charliedrage.com/kompose/

Fixed! Thank you.

**Comment by kadel** [comment]
One more thing. :angel: 
Couldn't you use `git checkout --orphan ... ` to create new empty branch? Than you don't have to delete all the files from master.

**Pull request closed without merging**
