### PR TITLE
implement storing to directory or file, add functional tests

### LINKED ISSUE #209: being able to store artifacts separately in a specific directory
Hi,

It would be great if I could store the generated provider artifacts to a specific directory other than the current working directory without having to bundling them into a single file (which `kompose convert -o ...`  currently does.

So, when `kompose convert -o artifacts` is run, if `artifacts` is a directory, then kompose should store all the resulting files inside it, and if it's not, then it should store the artifacts in a single file.

Thoughts?

### PR DESCRIPTION
**Pull request by containscafeine**
Fix #209

### CODE REVIEW

**Comment by surajssd** [comment]
wow Travis is still not started build

**Comment by cdrage** [comment]
It looks like the commit message is empty? I only see a title in there.

**Comment by containscafeine** [comment]
@cdrage, whoops, fixed!

**Comment by surajssd** [comment]
LGTM!

**Comment by cdrage** [comment]
Code LGTM, however @containscafeine mind explaining a little bit on the usage (how to use?). Seeing if we need to update the docs for this change :)

**Comment by containscafeine** [comment]
@surajssd @cdrage updated the usage for the flag -o. Should be good to go now?

**Comment by surajssd** [comment]
@containscafeine thanks merging it!

**Pull request merged**
