### PR TITLE
Update the example to include NodePort and accessability

### PR DESCRIPTION
**Pull request by cdrage**
This updates the example we have on the website to include NodePort in
the "labels" section as well as instructions on how to access the
service.

### CODE REVIEW

**Comment by cdrage** [comment]
ping @ngtuna @sebgoa @kadel

**Comment by cdrage** [comment]
Going to merge for now since the index page is the main page people are hitting and this is a common problem (how do I access the example?).

Let me know if there are any outstanding issues / problems!

**Comment by kadel** [comment]
Hmm, I'm not sure if we should encourage people to use nodePort. Using LoadBalancer would be much better.

**Comment by cdrage** [comment]
@kadel Only problem is that LoadBalancer is not supported in Minikube and those who want to try it would have to use a cloud provider with that supported :-1:

**Comment by surajssd** [comment]
@cdrage actually even if you convert the service as `LoadBalancer` it is still exposed as `NodePort`, so it's upto the user to provision a `LoadBalancer` and the values of it's IP address to be populated, but even if it's values are not populated the service should do just fine.

**Comment by kadel** [comment]
If you are using  minikube and you have LoadBalancer service you can access it using `minikube service <service name>` 

This is basically same think that @surajssd is talking about it is taking advantage of NodePort, but user doesn't have to know about it.

I don't like using NodeBalancer for accessing services directly from "outside", it won't work on most production clusters.

**Comment by cdrage** [comment]
@kadel 

Okay. So basically, switch to LoadBalancer in the example and in the tutorial tell them to simply check `kubectl get svc` for IP?

**Comment by kadel** [comment]
Yes.
I think that  switching to LoadBalancer would be better.
Than  for minikube keeping `minikube service frontend` and for other cases `kubectl get svc ....`

**Comment by cdrage** [comment]
@kadel Okay, #409 opened.

**Comment by kadel** [comment]
btw. one useful, but ugly command 😉 :

`kubectl get svc frontend -o template --template "{{(index .status.loadBalancer.ingress 0).ip}}:{{(index .spec.ports 0).port}}"`

this is will display public ip and port for frontend service

**Pull request merged**
