### PR TITLE
add deploy/undeploy pod only

### PR DESCRIPTION
**Pull request by ngtuna**
ref: #342

Ping @surajssd @kadel

### CODE REVIEW

**Comment by ngtuna** [comment]
@surajssd @kadel Do you have idea why my PR pulling down the coveralls ? :-(

**Comment by kadel** [comment]
@ngtuna because you added new lines that are not covered by tests :-)

**Comment by ngtuna** [comment]
@kadel oh now I got it. Test is coming up.

**Comment by kadel** [comment]
@ngtuna I'm not sure if this can be currently tested properly without mocking kubernetes :-( or starting cluster. 
But it would be great if you have any idea how to do it.
Otherwise I wouldn't worry about in this PR. We will have to figure out a way how to test up for everything later.

**Comment by ngtuna** [comment]
@kadel Right. I made this commit last night but then came up with no idea how to add a test. Will investigate it more late today.

**Comment by ngtuna** [comment]
@kadel I added commit for OpenShift

**Pull request merged**
