### PR TITLE
Add quickstart guide to docs

### PR DESCRIPTION
**Pull request by cdrage**
This doc is a direct copy from the one used on Kompose.io

Eventually, we will sync the documents in the /docs/ directory of this
repo to the gh-pages branch (as well as the Kubernetes page).

### CODE REVIEW

**Comment by kadel** [comment]
Would it make sense to add information on how to access deployed application?

**Comment by surajssd** [comment]
@kadel do you mean `kubectl` or `oc` commands?

**Comment by cdrage** [comment]
@surajssd I think he means curl'ing the application or checking http://localhost:80 for it.

**Comment by kadel** [comment]
> @surajssd I think he means curl'ing the application or checking http://localhost:80 for it.

That would be one of the options.
It would be nice to tell user how/where the application can be accessed.

**Comment by cdrage** [comment]
@kadel I've updated it in https://github.com/kubernetes-incubator/kompose/pull/409 so once that is merged, i'll update this PR.

**Comment by cdrage** [comment]
Closing for now

**Pull request closed without merging**
