### PR TITLE
Update vendoring as well as libcompose

### PR DESCRIPTION
**Pull request by cdrage**
This commit updates libcompose in order to merge in
https://github.com/docker/libcompose/pull/423 which affected
https://github.com/kubernetes-incubator/kompose/issues/92 by not
erroring out when an image name wasn't provided.

Closes https://github.com/kubernetes-incubator/kompose/issues/92

As well as knocks out the last required milestone for a 0.2.1 release
https://github.com/kubernetes-incubator/kompose/milestone/2

### CODE REVIEW

**Comment by cdrage** [comment]
ping @ngtuna as this closes your issue. 

With this PR, we will have completed all milestones for 0.2.1 which unblocks us for releasing a new version of kompose. https://github.com/kubernetes-incubator/kompose/milestone/2

**Comment by ngtuna** [comment]
+1 @cdrage. 

I was inserting a manual check for image while libcompose has not been updated, but your PR is here so we will work on this. Now I'm considering the test cases failing.

**Comment by cdrage** [comment]
@ngtuna @kadel So this seems to be failing due to:
```
▶ kompose --provider openshift -f /home/wikus/dropbox/dev/go/src/github.com/kubernetes-incubator/kompose/script/test/fixtures/tty-true/docker-compose.yml convert --stdout -j                                                                                                     
etes-incubator/kompose/script/test/fixtures/tty-true/output-oc.json                                                                                                                                                                                                               
WARN[0000] Unsupported root level networks key - ignoring                                                                                                          
{                                                                                                                         
  "kind": "List",                         
  "apiVersion": "v1",                
  "metadata": {},                                                                                                                                                                                                                                                                 
  "items": [                                                                                                                                                                                                                                                                      
    {                               
```

appearing..

Going to investigate this more.. But looks like an update to libcompose added that warning.

**Comment by kadel** [comment]
@cdrage 

There is a check that was testing root level networks before 
https://github.com/kubernetes-incubator/kompose/blob/4f176b847ec75f61ab69bcc03f2b759a178df991/pkg/loader/compose/compose.go#L87

It looks like new libcompose version is doing something little bit different with networks :-(

**Comment by cdrage** [comment]
@kadel yeah :( i saw, seems that it's something putting something into the file even though a network isn't there. I'll open up a separate PR for this to unblock this PR.

**Comment by kadel** [comment]
I don't think that we should merge this  if it is giving warning about root level network even there is none in docker-compose file. We should include fix in this pr.

**Comment by cdrage** [comment]
@kadel Done. I've added another commit to this PR that fixes the test.

**Comment by cdrage** [comment]
@ngtuna @surajssd can we get a quick review? :)

**Comment by ngtuna** [comment]
@cdrage LGTM

**Comment by surajssd** [comment]
@cdrage please uncomment this https://github.com/kubernetes-incubator/kompose/blob/master/script/test/cmd/tests.sh#L25

before we merge this!

**Comment by cdrage** [comment]
@surajssd 

Done. Have a quick look and give me the LGTM :+1: Then we can merge!

**Comment by cdrage** [comment]
@containscafeine I'll have to open up a separate PR in regards to updating libcompose as for some odd reason you can't do `glide update --strip-vendor` in a detached HEAD state when you do a git rebase.

Mind doing a quick LGTM so I can press that merge button?

**Comment by containscafeine** [comment]
@cdrage sure, lookin' gooood to me!!!

**Pull request merged**
