### PR TITLE
Update vendoring + fix issue with timestamps being added to log

### PR DESCRIPTION
**Pull request by cdrage**
As per the vendoring here:
https://github.com/kubernetes-incubator/kompose/commit/e9544ca89477ed76bd75f1160f9a89686f75e95d
for some odd issue, text_formatter.go in the logrus package was updated
to an older file.

This commit updates the vendoring as well as specifies a specific
version for logrus to be used.

### CODE REVIEW

**Comment by cdrage** [comment]
Closes #529

**Comment by sinnykumari** [comment]
Thanks Charlie! This commit looks good to me in terms of /vendor/golang.org/x/sys update and should fix issue#532

**Comment by dustymabe** [comment]
@cdrage, do you have any comprehensive tests you can run?

**Comment by dustymabe** [comment]
@cdrage can you add that this fixes #532 to the commit comment?

also I have a question, if we are updating a lot of different things then I think we might need a new release of kompose in order to put it out. would rather not pull back a patch if its going to be a large change.

**Comment by cdrage** [comment]
@dustymabe No comprehensive tests are being run right now, we're working on adding more integration tests. But unit tests + cmd tests are the only ones being ran at the moment.

Yup. We can do another release on Monday!

**Comment by dustymabe** [comment]
sounds good. once you commit PR we can have @surajssd build an rpm from this commit (don't need a release yet) and I can run it through the fedora build system to verify everything works on ppc **before you do a release**.

**Comment by cdrage** [comment]
I've confirmed that this commit works and we've gotten a LGTM.

Let's merge this!

**Pull request merged**
