### PR TITLE
Clarify tarball

### PR DESCRIPTION
**Pull request by cdrage**
Describe that it's a bandwidth-conservative alternative

### CODE REVIEW

**Comment by pradeepto** [comment]
Faster downloads, ah the small pleasures of life! @surajnarwade @surajssd @containscafeine @procrypt Can one of you please review and approve this?

**Comment by surajnarwade** [comment]
LGTM :)

**Comment by cdrage** [comment]
Since this is a doc change, only one LGTM is good!

Remember @surajnarwade to go through the review-process rather than LGTM so it's all green when it's merged :)

**Comment by procrypt** [comment]
LGTM :+1:

**Pull request merged**
