### PR TITLE
Update TRAVIS CI to add coveralls

### PR DESCRIPTION
**Pull request by cdrage**
Updates travis to enable coveralls support.

Fixes https://github.com/kubernetes-incubator/kompose/issues/281

### CODE REVIEW

**Comment by sebgoa** [comment]
I have access to coveralls via incubator. I will test this today.

**Comment by cdrage** [comment]
@sebgoa done. now let's see if these tests pass :)

**Comment by cdrage** [comment]
Currently this isn't working for some odd-reason (timing out). I'll be looking at an alternative fix.

**Comment by sebgoa** [comment]
ok, I am going to merge it and fix it

**Comment by kadel** [comment]
Why merge it if its not working?
It looks like it is missing token https://coveralls.zendesk.com/hc/en-us/articles/201342809-Go

**Comment by sebgoa** [comment]
because I was tired of seeing this PR pending and seeing our code coverage on the front page will be good motivation to improve unit tests.

afaik, you don't need a token for public repos...

but yeah it is failing.

**Comment by kadel** [comment]
To be honestly I don't see reason why it couldn't be fixed in this PR.

Now front page shows no coverage and failed tests.

I've done some digging around, and it is timeouting because it runs all unit test again for every package as separate `go test` run.
like this:
```
for package in all_packages:
   go test package
```
every go test package does new build, so it takes really long time, and travis-ci jobs has 15min timeout.

Root cause for this is that for some reason `go test ` can't collect coverage profile for multiple packages.
So you have to run it for every package again :-(


We could run tests and collect all coverageprofiles into one file  and than call `goveralls` with `-coverprofile` to only submit results to coveralls.io  as described here https://gist.github.com/rjeczalik/6f01430e8554bf59b88e

But it still requires to run `go test` for every package separately.

**Comment by kadel** [comment]
this is how kubernetes is dealing with this https://github.com/kubernetes/kubernetes/blob/master/hack/make-rules/test.sh#L228

**Pull request merged**
