### PR TITLE
Fix the examples

### PR DESCRIPTION
**Pull request by cdrage**
Moves `docker-compose.yaml` to `docker-compose-counter.yaml` and
replaces the default docker-compose.yaml with the example from the
Kompose.io website.

We also rename each file from yml to yaml.

As well as do some slight modifications / formatting to
docker-compose-bundle.dab

### CODE REVIEW

**Comment by cdrage** [comment]
Uh oh. Looks like we relied on those examples for some odd-reason in the tests. I'll update this.

**Comment by kadel** [comment]
I've noticed that you deleted `examples/docker-guestbook.yml` ?

**Comment by cdrage** [comment]
@kadel 

Yes. That's replaced by `docker-compose.yaml` which is the guestbook example we use on http://kompose.io

**Comment by cdrage** [comment]
@kadel `docker-compose.yaml` was missing since it was added to `.gitignore`. I've updated this PR.

**Comment by surajnarwade** [comment]
@cdrage , functional tests need to be updated as you renamed the file `docker-compose.yml` -> `docker-compose.yaml`

**Comment by kadel** [comment]
I'm lost in all this :-)

now you are reneaming `docker-guestbook.yml` to `docker-compose.yaml`?
Maybe you wanted `docker-guestbook.yaml`?

**Comment by cdrage** [comment]
@kadel 
Yes, I'm renaming it. If you check http://kompose.io both docker-guestbook.yaml and the example on the site is the same. Since it's our go-to-example. I've renamed docker-guestbook.yaml to docker-compose.yaml in the examples folder.

**Comment by cdrage** [comment]
@surajnarwade Yes, as referenced in this PR, https://github.com/kubernetes-incubator/kompose/pull/531 unblocks this PR.

**Comment by kadel** [comment]
> Yes, I'm renaming it. If you check http://kompose.io both docker-guestbook.yaml and the example on the site is the same. Since it's our go-to-example. I've renamed docker-guestbook.yaml to docker-compose.yaml in the examples folder.

OK

**Comment by kadel** [comment]
I guess this will need rebase once #531 is merged

**Comment by cdrage** [comment]
Rebased and waiting for Travis to pass then mergin'

**Comment by rmmh** [comment]
(test comment please ignore)

**Comment by cdrage** [comment]
Woop woop! Mergin' awayyy

**Pull request merged**
